"""Web3 integration layer for interacting with on-chain smart contracts.

Provides a :class:`BlockchainClient` that wraps calls to the four Solidity
contracts specified in the design document:

- **IdentityRegistry** – DID ↔ wallet mapping
- **BiometricCommitmentRegistry** – template commitment storage
- **AccessPolicyRegistry** – on-chain policy hashes
- **AuditLog** – immutable access-event log

All operations degrade gracefully when the blockchain provider is unavailable
or the ``web3`` package is not installed.
"""

from __future__ import annotations

import importlib.util
import json
import logging
import os
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

_WEB3_AVAILABLE = importlib.util.find_spec("web3") is not None

# Minimal ABIs – enough for the client to encode/decode calls.
# Full ABIs would be generated by `solc` and stored in a build artifact
# directory; these inline stubs keep the PoC self-contained.

_IDENTITY_REGISTRY_ABI: List[Dict[str, Any]] = [
    {
        "name": "registerIdentity",
        "type": "function",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "didHash", "type": "bytes32"},
            {"name": "wallet", "type": "address"},
        ],
        "outputs": [],
    },
    {
        "name": "rotateKey",
        "type": "function",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "didHash", "type": "bytes32"},
            {"name": "newWallet", "type": "address"},
        ],
        "outputs": [],
    },
    {
        "name": "identities",
        "type": "function",
        "stateMutability": "view",
        "inputs": [{"name": "", "type": "bytes32"}],
        "outputs": [
            {"name": "wallet", "type": "address"},
            {"name": "active", "type": "bool"},
            {"name": "registeredAt", "type": "uint256"},
        ],
    },
]

_COMMITMENT_REGISTRY_ABI: List[Dict[str, Any]] = [
    {
        "name": "storeCommitment",
        "type": "function",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "userId", "type": "bytes32"},
            {"name": "commitment", "type": "bytes32"},
            {"name": "version", "type": "string"},
            {"name": "storageURI", "type": "string"},
        ],
        "outputs": [],
    },
    {
        "name": "revokeCommitment",
        "type": "function",
        "stateMutability": "nonpayable",
        "inputs": [{"name": "userId", "type": "bytes32"}],
        "outputs": [],
    },
    {
        "name": "commitments",
        "type": "function",
        "stateMutability": "view",
        "inputs": [{"name": "", "type": "bytes32"}],
        "outputs": [
            {"name": "commitment", "type": "bytes32"},
            {"name": "version", "type": "string"},
            {"name": "storageURI", "type": "string"},
            {"name": "active", "type": "bool"},
            {"name": "updatedAt", "type": "uint256"},
        ],
    },
]

_AUDIT_LOG_ABI: List[Dict[str, Any]] = [
    {
        "name": "recordEvent",
        "type": "function",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "eventType", "type": "string"},
            {"name": "actorHash", "type": "bytes32"},
            {"name": "resourceHash", "type": "bytes32"},
            {"name": "outcome", "type": "string"},
        ],
        "outputs": [],
    },
]

_POLICY_REGISTRY_ABI: List[Dict[str, Any]] = [
    {
        "name": "setPolicy",
        "type": "function",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "resourceHash", "type": "bytes32"},
            {"name": "level", "type": "uint8"},
            {"name": "policyHash", "type": "bytes32"},
            {"name": "policyURI", "type": "string"},
        ],
        "outputs": [],
    },
]


@dataclass
class TxReceipt:
    tx_hash: str
    block_number: int
    status: int  # 1 = success


class BlockchainClient:
    """Thin wrapper around Web3.py for contract interactions.

    Instantiate with a provider URL and (optionally) contract addresses.
    If ``web3`` is not installed or the provider is unreachable, every
    public method returns ``None`` and logs a warning instead of raising.
    """

    def __init__(
        self,
        provider_url: str = "",
        private_key: str = "",
        identity_registry_addr: str = "",
        commitment_registry_addr: str = "",
        policy_registry_addr: str = "",
        audit_log_addr: str = "",
    ) -> None:
        self._enabled = False
        self._w3: Any = None
        self._account: Any = None
        self._identity_contract: Any = None
        self._commitment_contract: Any = None
        self._policy_contract: Any = None
        self._audit_contract: Any = None

        if not _WEB3_AVAILABLE:
            logger.warning("web3 package not installed – blockchain features disabled")
            return

        if not provider_url:
            logger.info("No WEB3_PROVIDER_URL configured – blockchain features disabled")
            return

        try:
            from web3 import Web3

            self._w3 = Web3(Web3.HTTPProvider(provider_url))
            if not self._w3.is_connected():
                logger.warning("Cannot connect to Web3 provider %s", provider_url)
                return

            if private_key:
                self._account = self._w3.eth.account.from_key(private_key)

            if identity_registry_addr:
                self._identity_contract = self._w3.eth.contract(
                    address=Web3.to_checksum_address(identity_registry_addr),
                    abi=_IDENTITY_REGISTRY_ABI,
                )
            if commitment_registry_addr:
                self._commitment_contract = self._w3.eth.contract(
                    address=Web3.to_checksum_address(commitment_registry_addr),
                    abi=_COMMITMENT_REGISTRY_ABI,
                )
            if policy_registry_addr:
                self._policy_contract = self._w3.eth.contract(
                    address=Web3.to_checksum_address(policy_registry_addr),
                    abi=_POLICY_REGISTRY_ABI,
                )
            if audit_log_addr:
                self._audit_contract = self._w3.eth.contract(
                    address=Web3.to_checksum_address(audit_log_addr),
                    abi=_AUDIT_LOG_ABI,
                )

            self._enabled = True
            logger.info("Blockchain client initialised (provider=%s)", provider_url)
        except Exception as exc:
            logger.warning("Blockchain client init failed: %s", exc)

    @property
    def is_enabled(self) -> bool:
        return self._enabled

    # ── helpers ───────────────────────────────────────────────

    def _send_tx(self, contract_fn: Any) -> Optional[TxReceipt]:
        if not self._enabled or not self._account:
            return None
        try:
            tx = contract_fn.build_transaction(
                {
                    "from": self._account.address,
                    "nonce": self._w3.eth.get_transaction_count(self._account.address),
                    "gas": 300_000,
                    "gasPrice": self._w3.eth.gas_price,
                }
            )
            signed = self._account.sign_transaction(tx)
            tx_hash = self._w3.eth.send_raw_transaction(signed.raw_transaction)
            receipt = self._w3.eth.wait_for_transaction_receipt(tx_hash, timeout=30)
            return TxReceipt(
                tx_hash=receipt.transactionHash.hex(),
                block_number=receipt.blockNumber,
                status=receipt.status,
            )
        except Exception as exc:
            logger.error("Blockchain tx failed: %s", exc)
            return None

    @staticmethod
    def _to_bytes32(value: str) -> bytes:
        """Convert a hex string or plain string to a 32-byte value."""
        import hashlib

        return hashlib.sha256(value.encode()).digest()

    # ── IdentityRegistry ─────────────────────────────────────

    def register_identity(self, did: str, wallet_address: str) -> Optional[TxReceipt]:
        if not self._identity_contract:
            logger.info("IdentityRegistry not configured – skipping on-chain registration")
            return None
        fn = self._identity_contract.functions.registerIdentity(
            self._to_bytes32(did),
            self._w3.to_checksum_address(wallet_address),
        )
        return self._send_tx(fn)

    def rotate_key(self, did: str, new_wallet: str) -> Optional[TxReceipt]:
        if not self._identity_contract:
            return None
        fn = self._identity_contract.functions.rotateKey(
            self._to_bytes32(did),
            self._w3.to_checksum_address(new_wallet),
        )
        return self._send_tx(fn)

    # ── BiometricCommitmentRegistry ──────────────────────────

    def store_commitment(
        self, user_id: str, commitment: str, version: str, storage_uri: str
    ) -> Optional[TxReceipt]:
        if not self._commitment_contract:
            logger.info("CommitmentRegistry not configured – skipping on-chain storage")
            return None
        fn = self._commitment_contract.functions.storeCommitment(
            self._to_bytes32(user_id),
            self._to_bytes32(commitment),
            version,
            storage_uri,
        )
        return self._send_tx(fn)

    def revoke_commitment(self, user_id: str) -> Optional[TxReceipt]:
        if not self._commitment_contract:
            return None
        fn = self._commitment_contract.functions.revokeCommitment(
            self._to_bytes32(user_id),
        )
        return self._send_tx(fn)

    # ── AuditLog ─────────────────────────────────────────────

    def record_audit_event(
        self, event_type: str, actor_did: str, resource: str, outcome: str
    ) -> Optional[TxReceipt]:
        if not self._audit_contract:
            return None
        fn = self._audit_contract.functions.recordEvent(
            event_type,
            self._to_bytes32(actor_did),
            self._to_bytes32(resource),
            outcome,
        )
        return self._send_tx(fn)

    # ── AccessPolicyRegistry ─────────────────────────────────

    def set_policy(
        self, resource: str, level: int, policy_hash: str, policy_uri: str
    ) -> Optional[TxReceipt]:
        if not self._policy_contract:
            return None
        fn = self._policy_contract.functions.setPolicy(
            self._to_bytes32(resource),
            level,
            self._to_bytes32(policy_hash),
            policy_uri,
        )
        return self._send_tx(fn)
