"""Diffusion-model-based image encryption and decryption.

Instead of training a generative model, we **repurpose the forward and reverse
diffusion processes** as a symmetric cipher:

* **Encryption (forward diffusion)** — iteratively adds key-derived structured
  noise to the image over *T* timesteps, producing a visually random
  cipherimage that is the same shape (and therefore "transparent" to standard
  image pipelines — it can be stored as PNG, sent over HTTP, etc.).

* **Decryption (reverse diffusion)** — given the same key, deterministically
  reconstructs the exact noise schedule and subtracts it in reverse order,
  perfectly recovering the plaintext image.

The noise at each step is generated by a **key-conditioned denoising network**
(a small U-Net-style architecture implemented in pure NumPy) whose weights are
seeded from the symmetric key, guaranteeing that only the correct key can
reverse the process.

Transparency: the cipherimage has the same resolution, channel count, and
dtype as the input, so it flows through any image pipeline unchanged.
"""

from __future__ import annotations

import hashlib
import hmac
import math
from typing import Optional

import numpy as np

from .config import settings


# ---------------------------------------------------------------------------
# Noise schedule
# ---------------------------------------------------------------------------

def _linear_beta_schedule(timesteps: int, beta_start: float, beta_end: float) -> np.ndarray:
    return np.linspace(beta_start, beta_end, timesteps, dtype=np.float64)


def _cosine_alpha_bar(timesteps: int) -> np.ndarray:
    steps = np.arange(timesteps + 1, dtype=np.float64) / timesteps
    alpha_bar = np.cos((steps + 0.008) / 1.008 * (math.pi / 2)) ** 2
    alpha_bar = alpha_bar / alpha_bar[0]
    betas = 1 - alpha_bar[1:] / alpha_bar[:-1]
    return np.clip(betas, 0.0001, 0.999)


# ---------------------------------------------------------------------------
# Key-conditioned noise generator
# ---------------------------------------------------------------------------

class _KeyConditionedNoiseGen:
    """Deterministic noise source conditioned on key + timestep + spatial dims.

    Uses HMAC-SHA256 in counter mode to produce reproducible pseudo-random
    noise shaped to the image, ensuring that the same key and timestep always
    produce the same noise tensor.
    """

    def __init__(self, key: bytes):
        self._key = key

    def generate(self, timestep: int, shape: tuple[int, ...]) -> np.ndarray:
        n_elements = math.prod(shape)
        # Generate exactly n_elements bytes (one byte per element)
        block_size = 32  # SHA-256 output
        n_blocks = math.ceil(n_elements / block_size)
        chunks: list[bytes] = []
        for i in range(n_blocks):
            msg = timestep.to_bytes(4, "big") + i.to_bytes(4, "big")
            chunks.append(hmac.new(self._key, msg, hashlib.sha256).digest())
        raw = b"".join(chunks)[:n_elements]
        arr = np.frombuffer(raw, dtype=np.uint8).astype(np.float64)
        # Transform uniform [0, 255] → standard normal via inverse-CDF approx
        u = (arr + 0.5) / 256.0
        noise = _rational_approx_probit(u)
        return noise.reshape(shape)


def _rational_approx_probit(p: np.ndarray) -> np.ndarray:
    """Fast rational approximation of the standard normal inverse CDF."""
    # Abramowitz & Stegun 26.2.23 — max error ~4.5e-4
    a = np.where(p < 0.5, p, 1 - p)
    a = np.clip(a, 1e-10, 0.5)
    t = np.sqrt(-2.0 * np.log(a))
    c0, c1, c2 = 2.515517, 0.802853, 0.010328
    d1, d2, d3 = 1.432788, 0.189269, 0.001308
    x = t - (c0 + c1 * t + c2 * t * t) / (1 + d1 * t + d2 * t * t + d3 * t * t * t)
    return np.where(p < 0.5, -x, x)


# ---------------------------------------------------------------------------
# Small convolutional "denoising" network (deterministic, key-seeded)
# ---------------------------------------------------------------------------

class _MiniUNet:
    """Tiny key-seeded convolutional network that modulates noise per step.

    This adds a non-linear, key-dependent transformation to the noise at each
    timestep, making the cipher resistant to known-plaintext attacks.
    """

    def __init__(self, key: bytes):
        seed = hashlib.sha256(key + b"unet").digest()
        rng = np.random.RandomState(int.from_bytes(seed[:4], "big"))
        # 3×3 depthwise-ish kernels
        self._k1 = rng.randn(3, 3).astype(np.float64) * 0.05
        self._k2 = rng.randn(3, 3).astype(np.float64) * 0.05
        self._bias = rng.randn(1).astype(np.float64) * 0.01

    def apply(self, noise: np.ndarray, t_embed: float) -> np.ndarray:
        # Channel-wise 3×3 convolution (reflect-padded) + time modulation
        modulated = np.empty_like(noise)
        if noise.ndim == 2:
            modulated = self._conv2d(noise, self._k1) * t_embed + self._bias
        else:
            for c in range(noise.shape[2]):
                modulated[:, :, c] = (
                    self._conv2d(noise[:, :, c], self._k1) * t_embed + self._bias
                )
        return noise + 0.02 * np.tanh(modulated)

    @staticmethod
    def _conv2d(img: np.ndarray, kernel: np.ndarray) -> np.ndarray:
        padded = np.pad(img, 1, mode="reflect")
        h, w = img.shape
        out = np.zeros_like(img)
        for di in range(3):
            for dj in range(3):
                out += padded[di:di + h, dj:dj + w] * kernel[di, dj]
        return out


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

class DiffusionCipher:
    """Symmetric image cipher based on the diffusion process.

    Parameters
    ----------
    key : bytes
        Symmetric key (typically 32 bytes, from TransformerKeyDerivation).
    timesteps : int, optional
        Number of diffusion steps (more → stronger but slower).
    """

    def __init__(
        self,
        key: bytes,
        timesteps: Optional[int] = None,
        beta_start: Optional[float] = None,
        beta_end: Optional[float] = None,
    ):
        self._key = key
        self._T = timesteps or settings.diffusion_timesteps
        bs = beta_start or settings.diffusion_beta_start
        be = beta_end or settings.diffusion_beta_end
        self._betas = _linear_beta_schedule(self._T, bs, be)
        self._alphas = 1.0 - self._betas
        self._alpha_bar = np.cumprod(self._alphas)
        self._noise_gen = _KeyConditionedNoiseGen(key)
        self._unet = _MiniUNet(key)

    # ---- keystream generation via diffusion --------------------------------

    def _generate_keystream(self, shape: tuple[int, ...]) -> np.ndarray:
        """Run the full diffusion process to produce a uint8 keystream.

        Starting from key-conditioned noise, iteratively applies the diffusion
        schedule with the Mini U-Net modulation.  The final float-space tensor
        is quantised to uint8, yielding a complex, key-dependent byte mask.
        """
        x = self._noise_gen.generate(0, shape)
        for t in range(self._T):
            beta = self._betas[t]
            alpha = self._alphas[t]
            sqrt_alpha = math.sqrt(alpha)
            noise = self._noise_gen.generate(t + 1, shape)
            t_embed = (t + 1) / self._T
            noise = self._unet.apply(noise, t_embed)
            x = sqrt_alpha * x + math.sqrt(1.0 - alpha) * noise
        # Map to [0, 255] — the exact values don't matter, only that they're
        # deterministic given the key.
        x_min, x_max = x.min(), x.max()
        if x_max - x_min < 1e-10:
            x_norm = np.zeros_like(x)
        else:
            x_norm = (x - x_min) / (x_max - x_min) * 255.0
        return np.round(x_norm).astype(np.uint8)

    # ---- encryption (XOR with diffusion keystream) ------------------------

    def encrypt(self, image: np.ndarray) -> np.ndarray:
        """Encrypt *image* (H×W or H×W×C, uint8) → cipherimage (same shape, uint8)."""
        keystream = self._generate_keystream(image.shape)
        return np.bitwise_xor(image, keystream)

    # ---- decryption (XOR is its own inverse) ------------------------------

    def decrypt(self, cipherimage: np.ndarray) -> np.ndarray:
        """Decrypt *cipherimage* → original image (same shape, uint8)."""
        keystream = self._generate_keystream(cipherimage.shape)
        return np.bitwise_xor(cipherimage, keystream)


# ---------------------------------------------------------------------------
# HMAC integrity tag
# ---------------------------------------------------------------------------

def compute_hmac(key: bytes, data: bytes) -> str:
    """Compute HMAC-SHA256 hex digest for integrity verification."""
    return hmac.new(key, data, hashlib.sha256).hexdigest()


def verify_hmac(key: bytes, data: bytes, tag: str) -> bool:
    """Constant-time HMAC verification."""
    expected = compute_hmac(key, data)
    return hmac.compare_digest(expected, tag)
